// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    Resource: require('./resource'),
    ResourceServer: require('./resource-server'),
    Server: require('./server')
  };

}).call(this);
