// Generated by CoffeeScript 1.8.0
(function() {
  var ResourceServer, Server, bodyParser, express, passParentParams, pathLib;

  express = require('express');

  bodyParser = require('body-parser');

  ResourceServer = require('./resource-server');

  pathLib = require('path');

  Server = function(options) {
    var fail, registered, resources, server;
    if (options == null) {
      options = {};
    }
    registered = [];
    resources = {};
    server = express();
    if (typeof options.config === "function") {
      options.config(server);
    }
    server.use(bodyParser());
    fail = function(message, code) {
      if (code == null) {
        code = 404;
      }
      throw {
        message: message,
        code: code
      };
    };
    server.use(function(req, res, next) {
      req.serverResources = resources;
      return next();
    });
    server.on("error", function(err) {
      return console.error(err);
    });
    server.get("/", function(req, res) {
      return res.send(registered.map(function(register) {
        return {
          name: register.resource.name,
          url: register.path
        };
      }));
    });
    server.register = function(resource, nestedResource) {
      var npath, parentId, path, resourceServer;
      path = "/" + resource.pluralName;
      if (nestedResource) {
        resourceServer = new ResourceServer(nestedResource);
        parentId = "" + resource.name + "Id";
        resourceServer.addFilter('GET /', function(req, record) {
          return record[parentId] === req.params[parentId];
        });
        nestedResource.addValidator(function(record) {
          var errors;
          if (!resource.find(record[parentId])) {
            errors = {};
            errors[parentId] = ["" + resource.name + " with id=" + record[parentId] + " does not exist"];
            return errors;
          } else {
            return void 0;
          }
        });
        npath = "" + path + "/:" + parentId + "/" + nestedResource.pluralName;
        server.use(npath, passParentParams);
        server.use(npath, resourceServer);
        registered.push({
          path: npath,
          resource: nestedResource
        });
      } else {
        resourceServer = new ResourceServer(resource);
        server.use(path, resourceServer);
        registered.push({
          path: path,
          resource: resource
        });
      }
      resources[resource.pluralName] = resource;
      return this;
    };
    return server;
  };

  passParentParams = function(req, res, next) {
    var param, val, _ref;
    req.parentParams = req.params;
    _ref = req.parentParams;
    for (param in _ref) {
      val = _ref[param];
      if (param.match(/Id$/)) {
        req.parentParams[param] = parseInt(val);
      }
    }
    return next();
  };

  module.exports = Server;

}).call(this);
